version: 2

sources:
  - name: staging
    database: symmetric-span-450300-d4
    schema: trips_data_all
    tables:
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_green_tripdata
  - name: stg_yellow_tripdata  